# -*- makefile-gmake -*-
M=Main_Library
P=Proof_of_Extensionality
COQFLAGS = -opt -q
MADE_FILES = 
%.glob %.vo: %.v
	@ echo "make: Entering directory \`$(dir $*)'"
	cd $(dir $*) && coqc $(COQFLAGS) $(notdir $*.v)
	@ echo "make: Leaving directory \`$(dir $*)'"
all: 							\
	$M/Generalities/uu0.vo				\
	$M/Generalities/uu1.vo				\
	$M/Generalities/uu1uu0.vo			\
	$P/univ01.vo					\
	$M/hlevel1/hProp.vo				\
	$M/hlevel2/finite_sets.vo			\
	$M/hlevel1/hProp_up.vo				\
	$M/hlevel1/hProp_r.vo				\
	$M/hlevel1/hProp_r_up.vo			\
	$M/hlevel2/hSet_r.vo				\
	$M/hlevel2/hSet_r_up.vo				\
	$M/hlevel2/set_quotients_constr2_r_up.vo	\
	$M/hlevel2/set_quotients_r_up.vo

MADE_FILES += $M/Generalities/uu1.v
$M/Generalities/uu1.v: $M/Generalities/uu0.v
	rm -f $@
	(echo '(****** do not edit this file, it is a copy of uu0.v ******)'; \
		cat $< \
		) >$@ ; chmod a-w $@

$P/univ01.vo $M/Generalities/uu1uu0.vo: $M/Generalities/uu0.vo $M/Generalities/uu1.vo
clean: Main_Library-clean Proof_of_Extensionality-clean
	rm -f $(MADE_FILES)
Main_Library-clean:
	rm -f $M/*.aux $M/*.dvi $M/*.idx $M/*.log $M/*.aux $M/*.glob $M/*.vo $M/*.pdf
Proof_of_Extensionality-clean:
	rm -f $P/*.aux $P/*.dvi $P/*.idx $P/*.log $P/*.aux $P/*.glob $P/*.vo $P/*.pdf
